<a href="https://colab.research.google.com/github/JeetDodiy/Numpy/blob/main/learnig_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Start Numpy

In [1]:
# Frist Step was Import Numpy library
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
# Where the List Was give in arry the achange the ther data type to one single data type
# in the List any one data was string the arry chang all the data in to sting formate
a = [4,5,4.5,'jeet']
np.array(a)
# where in list all data in int and one one data was in float arry chang all the data and give float data type
b = [5,6,8.5]
np.array(b)

array([5. , 6. , 8.5])

# Arrys Type


In [ ]:
# in Numpay array there manly Three type of array have
# (1) Vactor [1D] ex. [4 ,] one Row
# (2) Matrix [2D] ex. [2,2] two Row and Two column
# (3) Tensor [3D +] ex. [2,2,2] 2 lear , 2 row , 2 cloumn

In [ ]:
# This is called Matrix [2D (3 Row ,3 Column)]
l = ([[1,2,3],
    [4,5,6],
    [7,8,9]])
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# This is called Tansor [3D (3 lear,3 Row ,3 Column)]
tansor = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print("dai" , tansor.ndim)
print("shap" , tansor.shape)
tansor

dai 3
shap (3, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

# Functions and Methods


In [ ]:
# In numpy arange was also same function like range function python.
# arange = np.arange(1,11)
# arange
arange = np.arange(1,11,2)
arange


array([1, 3, 5, 7, 9])

In [ ]:
# The Zeros function use to crate n number of zero
zeroDemo = np.zeros((6,5),dtype=int)
zeroDemo

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# the Ones also semelar to Zeros
onesDemo = np.ones((6,5),dtype=int)
onesDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# the Linspace was use to generate spacing betwen 2 numbers and the space was same of all the time
liniarspaceDemo = np.linspace(1,2,7)
liniarspaceDemo

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [ ]:
# The ramndom mathod use to generate random value in random sum difrent method also acsist
# random.rand,
# random.randn

In [ ]:
# random.rand method use to generat value 0 to 1 thats calld normalization
a = np.random.rand(5)
a

array([0.03453237, 0.21238359, 0.78175248, 0.80461323, 0.12584876])

In [ ]:
# random.randn method use to generat value -3 to 3 thats calld  standardization
a = np.random.randn(15)
a

array([-0.58732039, -0.277543  ,  0.04893099,  1.17187501, -0.17624833,
        1.05389687, -1.25405603,  0.68432573, -0.40096856,  0.44482866,
        0.71014988,  1.18151896, -0.07318696,  1.55362971, -0.14461455])

In [ ]:
# random.randint method use to genrat value was given
a = np.random.randint(1,15,5)
a
# this method generat value biwen given low(first) value , high(secand)value and threed was given difrece  between

array([ 7, 12,  8,  3, 13])

In [ ]:
# Arry attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# arr.shape

In [ ]:
# arr.size

In [ ]:
# arr.dtype

# Arry Methods

In [ ]:
# Arry Methods

In [ ]:
print(arr.min())

1


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.sum())

45


In [ ]:
print(np.sum(arr,axis=0))

[12 15 18]


In [ ]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [ ]:
print(arr.mean())

5.0


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.std() )

2.581988897471611


In [ ]:
print(arr.argmax())

8


In [ ]:
print(arr.argmin())

0


In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# To create Normal array ro matrix use reshape mathod
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Numpy Indexing and slicing of victors

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# Indexing
print(arr[9])

20


In [ ]:
# SLICING
print(arr[1:5])

[12 13 14 15]


In [ ]:
# In arr[Starting point : Ending Point : Steps]
print(arr[1::2])

[12 14 16 18 20]


# Numpy Indexing and slicing of Matrix

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
print(arr[2,2])

13


In [ ]:
print(arr[2])

[11 12 13 14 15]


In [ ]:
# in slicing arr[starting row : Ending Row , Starting  column : Ending column]
slaces = arr[2:4,3:5]
slaces

array([[14, 15],
       [19, 20]])

In [ ]:
sla = arr[3:6,3:5]
sla

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
# Slecet the one Column arr[ empty row : empty row  , sarting column : Ending Column]
s = arr[:,4:]
s

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30]])

 # Boolean Indexing

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index =  arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

 # **ARRAY OPRATIONS**

 # Arithmatic Opration

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1 // a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [ ]:
l = [10 , 20 ,30 , 40 ,50 ]
arr = np.array(l)

In [ ]:
arr + 10

array([20, 30, 40, 50, 60])

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
print(arr.min())

1


In [ ]:
print(arr.mean())

15.5


In [ ]:
print(arr.max())

30


In [ ]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

# Deep And Shallow Copy

In [ ]:
# In array all the opraction not aplide the real value of main array
#  where the arr was doing any opration use Shallow copy
# shallow copy means that can not copy path use chang the value in secand variyabel but firest variyable can not efectaed
# this was effacet onliy arry opration or matheds
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice = a[:5]
slice


array([1, 2, 3, 4, 5])

In [ ]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# this is called Hard Copy
b = a
b[0] = 100
b = b *10
b

array([1000,   20,   30,   40,   50,   60,   70,   80,   90,  100])

In [ ]:
# the shallow copy working onliy arryas method
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a2


array([[5, 6],
       [7, 8]])

In [ ]:
#this opracction use to maltiplay the matrix use of maltiplay the matrix was two way
# (1) use @
a1 @ a2
# (2) use np.dot()
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [ ]:
a1

array([[1, 2],
       [3, 4]])

In [ ]:
# tranfos use to transfor full matrax row to columan and columan in to row
a1 = a1.T

In [ ]:
a1

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation


*   Stacking Array
*   Spliting Array



**Stacking Array**

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [ ]:
# This Stacke Use for Vartical Sacking the Array
C = np.vstack((A,B))
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# This Stacke Use for Horizontaliy Sacking the Array
D = np.hstack((A,B))
D

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
# This Stacke Use for Column vaise Sacking the Array

E = np.column_stack((A,B))
E

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

**SPliting Array**

In [ ]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# this is use for Horizantal shlipt
# np.hsplit(array name,split Value)
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
# this is use for Vartical split
# np.vsplit(array name,split Value)
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# use for print
a = np.vsplit(c,4)
for i in a:
  print(i)


[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


# Exersises

**Valid Sudoku**

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Question**

In [4]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students.
print(data.mean())

61.06666666666667


In [ ]:
#Extract Math marks of all students.
sa = data[:,1]
sa

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
data[:,2].max()

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
for i in data[:,1]:
  if 90 < i:
    print(i)


92


In [ ]:
#Increase Math marks of all students by 5.
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
j = 0
for i in data[:,0]:
  if i<19:
    j =j + 1
print(j)

3


In [ ]:
#Calculate the average marks in each subject (column-wise mean).
# Math
data[:,1:].mean()

np.float64(82.4)

In [6]:
# Scince
data[:,2:].mean()


np.float64(83.2)

In [11]:
 #Get data of students who scored at least 80 in both subjects.
for i in data[:,1:]:
  if i[0] > 80 and i[1] > 80:
    print(i)


[92 88]
[90 85]


In [12]:
# Replace all Science marks < 75 with 0.
for i in data[:,2]:
  if i < 75:
    i = 0
    print(i)


0


In [15]:
data[data[:,2] < 75, 2] = 0
display(data)

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])