<a href="https://colab.research.google.com/github/JeetDodiy/Numpy/blob/main/learnig_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Frist Stap was Import Numpy library
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
# Where the List Was give in arry the achange the ther data type to one single data type
# in the List any one data was string the arry chang all the data in to sting formate
a = [4,5,4.5,'jeet']
np.array(a)
# where in list all data in int and one one data was in float arry chang all the data and give float data type
b = [5,6,8.5]
np.array(b)

array([5. , 6. , 8.5])

In [13]:
# in Numpay array there manly Three type of array have
# (1) Vactor [1D] ex. [4 ,] one Row
# (2) Matrix [2D] ex. [2,2] two Row and Two column
# (3) Tensor [3D +] ex. [2,2,2] 2 lear , 2 row , 2 cloumn

In [21]:
# This is called Matrix [2D (3 Row ,3 Column)]
l = ([[1,2,3],
    [4,5,6],
    [7,8,9]])
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# This is called Tansor [3D (3 lear,3 Row ,3 Column)]
tansor = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print("dai" , tansor.ndim)
print("shap" , tansor.shape)
tansor

dai 3
shap (3, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
# In numpy arange was also same function like range function python.
# arange = np.arange(1,11)
# arange
arange = np.arange(1,11,2)
arange


array([1, 3, 5, 7, 9])

In [30]:
# The Zeros function use to crate n number of zero
zeroDemo = np.zeros((6,5),dtype=int)
zeroDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# the Ones also semelar to Zeros
onesDemo = np.ones((6,5),dtype=int)
onesDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
# the Linspace was use to generate spacing betwen 2 numbers and the space was same of all the time
liniarspaceDemo = np.linspace(1,2,7)
liniarspaceDemo

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])