<a href="https://colab.research.google.com/github/JeetDodiy/Numpy/blob/main/learnig_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Start Numpy

In [29]:
# Frist Step was Import Numpy library
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Where the List Was give in arry the achange the ther data type to one single data type
# in the List any one data was string the arry chang all the data in to sting formate
a = [4,5,4.5,'jeet']
np.array(a)
# where in list all data in int and one one data was in float arry chang all the data and give float data type
b = [5,6,8.5]
np.array(b)

array([5. , 6. , 8.5])

# Arrys Type


In [ ]:
# in Numpay array there manly Three type of array have
# (1) Vactor [1D] ex. [4 ,] one Row
# (2) Matrix [2D] ex. [2,2] two Row and Two column
# (3) Tensor [3D +] ex. [2,2,2] 2 lear , 2 row , 2 cloumn

In [ ]:
# This is called Matrix [2D (3 Row ,3 Column)]
l = ([[1,2,3],
    [4,5,6],
    [7,8,9]])
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# This is called Tansor [3D (3 lear,3 Row ,3 Column)]
tansor = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print("dai" , tansor.ndim)
print("shap" , tansor.shape)
tansor

dai 3
shap (3, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

# Functions and Methods


In [ ]:
# In numpy arange was also same function like range function python.
# arange = np.arange(1,11)
# arange
arange = np.arange(1,11,2)
arange


array([1, 3, 5, 7, 9])

In [ ]:
# The Zeros function use to crate n number of zero
zeroDemo = np.zeros((6,5),dtype=int)
zeroDemo

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# the Ones also semelar to Zeros
onesDemo = np.ones((6,5),dtype=int)
onesDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# the Linspace was use to generate spacing betwen 2 numbers and the space was same of all the time
liniarspaceDemo = np.linspace(1,2,7)
liniarspaceDemo

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [ ]:
# The ramndom mathod use to generate random value in random sum difrent method also acsist
# random.rand,
# random.randn

In [ ]:
# random.rand method use to generat value 0 to 1 thats calld normalization
a = np.random.rand(5)
a

array([0.03453237, 0.21238359, 0.78175248, 0.80461323, 0.12584876])

In [ ]:
# random.randn method use to generat value -3 to 3 thats calld  standardization
a = np.random.randn(15)
a

array([-0.58732039, -0.277543  ,  0.04893099,  1.17187501, -0.17624833,
        1.05389687, -1.25405603,  0.68432573, -0.40096856,  0.44482866,
        0.71014988,  1.18151896, -0.07318696,  1.55362971, -0.14461455])

In [ ]:
# random.randint method use to genrat value was given
a = np.random.randint(1,15,5)
a
# this method generat value biwen given low(first) value , high(secand)value and threed was given difrece  between

array([ 7, 12,  8,  3, 13])

In [ ]:
# Arry attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# arr.shape

In [ ]:
# arr.size

In [ ]:
# arr.dtype

# Arry Methods

In [ ]:
# Arry Methods

In [ ]:
print(arr.min())

1


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.sum())

45


In [ ]:
print(np.sum(arr,axis=0))

[12 15 18]


In [ ]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [ ]:
print(arr.mean())

5.0


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.std() )

2.581988897471611


In [ ]:
print(arr.argmax())

8


In [ ]:
print(arr.argmin())

0


In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# To create Normal array ro matrix use reshape mathod
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Numpy Indexing and slicing of victors

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
# Indexing
print(arr[9])

20


In [8]:
# SLICING
print(arr[1:5])

[12 13 14 15]


In [9]:
# In arr[Starting point : Ending Point : Steps]
print(arr[1::2])

[12 14 16 18 20]


# Numpy Indexing and slicing of Matrix

In [19]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
print(arr[2,2])

13


In [21]:
print(arr[2])

[11 12 13 14 15]


In [25]:
# in slicing arr[starting row : Ending Row , Starting  column : Ending column]
slaces = arr[2:4,3:5]
slaces

array([[14, 15],
       [19, 20]])

In [27]:
sla = arr[3:6,3:5]
sla

array([[19, 20],
       [24, 25],
       [29, 30]])

In [28]:
# Slecet the one Column arr[ empty row : empty row  , sarting column : Ending Column]
s = arr[:,4:]
s

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30]])

 # Boolean Indexing

In [38]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_index =  arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [40]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])