<a href="https://colab.research.google.com/github/JeetDodiy/Numpy/blob/main/learnig_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
# Frist Stap was Import Numpy library
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
# Where the List Was give in arry the achange the ther data type to one single data type
# in the List any one data was string the arry chang all the data in to sting formate
a = [4,5,4.5,'jeet']
np.array(a)
# where in list all data in int and one one data was in float arry chang all the data and give float data type
b = [5,6,8.5]
np.array(b)

array([5. , 6. , 8.5])

In [13]:
# in Numpay array there manly Three type of array have
# (1) Vactor [1D] ex. [4 ,] one Row
# (2) Matrix [2D] ex. [2,2] two Row and Two column
# (3) Tensor [3D +] ex. [2,2,2] 2 lear , 2 row , 2 cloumn

In [21]:
# This is called Matrix [2D (3 Row ,3 Column)]
l = ([[1,2,3],
    [4,5,6],
    [7,8,9]])
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# This is called Tansor [3D (3 lear,3 Row ,3 Column)]
tansor = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print("dai" , tansor.ndim)
print("shap" , tansor.shape)
tansor

dai 3
shap (3, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
# In numpy arange was also same function like range function python.
# arange = np.arange(1,11)
# arange
arange = np.arange(1,11,2)
arange


array([1, 3, 5, 7, 9])

In [30]:
# The Zeros function use to crate n number of zero
zeroDemo = np.zeros((6,5),dtype=int)
zeroDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# the Ones also semelar to Zeros
onesDemo = np.ones((6,5),dtype=int)
onesDemo

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
# the Linspace was use to generate spacing betwen 2 numbers and the space was same of all the time
liniarspaceDemo = np.linspace(1,2,7)
liniarspaceDemo

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [9]:
# The ramndom mathod use to generate random value in random sum difrent method also acsist
# random.rand,
# random.randn

In [11]:
# random.rand method use to generat value 0 to 1 thats calld normalization
a = np.random.rand(5)
a

array([[0.71185782, 0.50331689, 0.49297457, 0.4603133 , 0.8103343 ]])

In [16]:
# random.randn method use to generat value -3 to 3 thats calld  standardization
a = np.random.randn(15)
a

array([-1.20408162, -0.11662143,  0.52645286, -0.86123386, -0.51982571,
       -0.4814603 ,  0.21279556, -1.07301506,  0.74912485, -2.1934074 ,
        2.12089147,  2.02957383, -0.86797426,  2.16656078,  0.03045047])

In [17]:
# random.randint method use to genrat value was given
a = np.random.randint(1,15,5)
a
# this method generat value biwen given low(first) value , high(secand)value and threed was given difrece  between

array([10,  6,  4, 11,  3])

In [37]:
# Arry attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# arr.shape

(3, 3)

In [28]:
# arr.size

9

In [32]:
# arr.dtype

dtype('int64')

In [34]:
# Arry Methods

In [42]:
print(arr.min())

1


In [43]:
print(arr.max())

9


In [44]:
print(arr.sum())

45


In [46]:
print(np.sum(arr,axis=0))

[12 15 18]


In [48]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [50]:
print(arr.mean())

5.0


In [51]:
print(arr.max())

9


In [53]:
print(arr.std() )

2.581988897471611


In [55]:
print(arr.argmax())

8


In [56]:
print(arr.argmin())

0


In [62]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:
# To create Normal array ro matrix use reshape mathod
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])